# autogenerated by txs
\dayofweeknameidenglish{arg1}#S
\monthnameenglish#S
\monthnameenglish[opt]#S
\ordinaldateenglish{arg1}#S
\shortdayofweeknameidenglish{arg1}#S
\shortmonthnameenglish#S
\shortmonthnameenglish[opt]#S
\\monthnameenglish#S
\\shortmonthnameenglish#S
