# autogenerated by txs
\CaptionLabelFont#S
\CaptionLabelSeparator#S
\CaptionTextFont#S
\DeclareCurrentRelease{arg1}{arg2}#S
\DeclareRelease{arg1}{arg2}{arg3}#S
\FBifLTcapwidth{arg1}#S
\LT#S
\LTcaptype#S
\caption#S
\captionnewline#S
\ext#S
\next#S
\refstepcounter#S
