#!/usr/bin/env bash
# check_no_name_directories.sh - Monitor and report no_name_error topic directories
# Purpose: Detect topic naming agent failures for debugging and quality monitoring
# Exit codes: 0 (no failures), 1 (failures found)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Default specs directory
SPECS_DIR="${CLAUDE_SPECS_ROOT:-$PROJECT_ROOT/.claude/specs}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Usage information
usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Monitor .claude/specs/ directory for topic naming failures (no_name_error directories).

OPTIONS:
  -h, --help     Show this help message
  -q, --quiet    Quiet mode (only show count)
  -v, --verbose  Verbose mode (show details)

ENVIRONMENT:
  CLAUDE_SPECS_ROOT  Override specs directory location

EXIT CODES:
  0  No no_name_error directories found (success)
  1  One or more no_name_error directories found (failure)

EXAMPLES:
  # Check for naming failures
  $0

  # Use in CI pipeline (exit 1 if failures exist)
  $0 || echo "Topic naming failures detected"

  # Quiet mode for scripting
  $0 -q
EOF
}

# Parse options
QUIET=false
VERBOSE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      exit 0
      ;;
    -q|--quiet)
      QUIET=true
      shift
      ;;
    -v|--verbose)
      VERBOSE=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

# Check if specs directory exists
if [ ! -d "$SPECS_DIR" ]; then
  if [ "$QUIET" = false ]; then
    echo "Specs directory not found: $SPECS_DIR"
  fi
  exit 0  # Not an error, just no directory to check
fi

# Find all no_name directories
NO_NAME_DIRS=()
while IFS= read -r dir; do
  NO_NAME_DIRS+=("$dir")
done < <(find "$SPECS_DIR" -type d -name '*_no_name_error' 2>/dev/null | sort)

# Count results
COUNT=${#NO_NAME_DIRS[@]}

# Quiet mode: just print count
if [ "$QUIET" = true ]; then
  echo "$COUNT"
  [ $COUNT -eq 0 ] && exit 0 || exit 1
fi

# Header
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Topic Naming Agent Failure Monitor"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Specs Directory: $SPECS_DIR"
echo ""

# Report results
if [ $COUNT -eq 0 ]; then
  echo -e "${GREEN}✓ No topic naming failures found${NC}"
  echo ""
  echo "All topics have semantic names generated by the topic-naming-agent."
  exit 0
else
  echo -e "${RED}✗ Found $COUNT topic naming failure(s)${NC}"
  echo ""

  # List directories
  echo "No_name_error directories:"
  for dir in "${NO_NAME_DIRS[@]}"; do
    # Extract topic number
    topic_num=$(basename "$dir" | sed 's/_no_name_error$//')
    echo "  - $dir"

    # Verbose mode: show directory contents
    if [ "$VERBOSE" = true ]; then
      echo "    Contents:"
      ls -1 "$dir" 2>/dev/null | sed 's/^/      - /' || echo "      (empty)"
    fi
  done

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Recommended Actions"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "1. Investigate naming failures:"
  echo "   /errors --type agent_error --command /plan"
  echo "   /errors --type validation_error"
  echo ""
  echo "2. Rename failed directories:"
  echo "   $SCRIPT_DIR/rename_no_name_directory.sh <directory> <new_name>"
  echo ""
  echo "3. Analyze error patterns:"
  echo "   /repair --type agent_error --complexity 2"
  echo ""

  exit 1
fi
