-- local status_ok, autolist = pcall(require, "autolist")
-- if not status_ok then
--   return
-- end
--
-- autolist.setup({
--   ft = {
--     "markdown",
--     "text",
--     "tex",
--     "plaintex",
--   },
--   config = function()
--     autolist.create_mapping_hook("i", "<CR>", autolist.new)
--     autolist.create_mapping_hook("i", "<Tab>", autolist.indent)
--     autolist.create_mapping_hook("i", "<S-Tab>", autolist.indent, "<C-D>")
--     autolist.create_mapping_hook("n", "o", autolist.new)
--     autolist.create_mapping_hook("n", "O", autolist.new_before)
--     autolist.create_mapping_hook("n", ">>", autolist.indent)
--     autolist.create_mapping_hook("n", "<<", autolist.indent)
--     autolist.create_mapping_hook("n", "<leader>r", autolist.force_recalculate)
--     autolist.create_mapping_hook("n", "<leader>x", autolist.invert_entry, "")
--       vim.api.nvim_create_autocmd("TextChanged", {
--         pattern = "-",
--         callback = function()
--           vim.cmd.normal({autolist.force_recalculate(nil, nil), bang = false})
--         end
--       })
--   end,
-- })
--
	-- lists = {
	-- 		markdown = {
	-- 			"%a[.)]", -- insert your custom lua pattern here
	-- 			"test", -- or use the test pattern defined below
	-- 		},
	-- 	},
	-- list_patterns = {
	-- 	test = "%a[.)]", -- insert your custom lua pattern here
	-- }
